name: "iwslt14-deen-bpe"

data:
    src: "de"
    trg: "en"
    train: "test/data/iwslt14/train"
    dev: "test/data/iwslt14/valid" 
    test: "test/data/iwslt14/test"
    level: "word"
    lowercase: True
    max_sent_length: 64
    src_voc_min_freq: 1
    src_voc_limit: 3200 # FIXME change this later! 
    trg_voc_min_freq: 1
    trg_voc_limit: 3200
    src_vocab: "test/data/iwslt14/vocab.txt"
    trg_vocab: "test/data/iwslt14/vocab.txt"

testing:
    beam_size: 1
    alpha: 1.0

training:
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.05
    batch_size: 128
    scheduling: "plateau"
    patience: 8
    clip_grad_norm: 1.0
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "loss"
    loss_function: "xent"
    epochs: 100
    validation_freq: 100
    logging_freq: 80
    eval_metric: "bleu"
    model_dir: "models/iwslt14_deen_bpe"
    overwrite: True
    shuffle: True
    use_cuda: True
    max_output_length: 80
    print_valid_sents: [0, 1, 2, 3, 4]

model:
    tied_embeddings: True
    encoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 300
            scale: False
        hidden_size: 200
        bidirectional: True
        dropout: 0.0
        num_layers: 2
    decoder:
        rnn_type: "lstm"
        embeddings:
            embedding_dim: 300
            scale: False
        emb_scale: False
        hidden_size: 200
        dropout: 0.0
        hidden_dropout: 0.2
        num_layers: 2
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
        out_type: "vocab"
