name: "reverse_experiment"

data:
    src: "src"
    trg: "trg"
    train: "train"
    dev: "dev"
    test: "test"
    level: "word"
    lowercase: False
    max_sent_length: 25
    voc_min_freq: 0
    voc_limit: 100
    #src_vocab: "my_model/src_vocab.txt"
    #trg_vocab: "my_model/trg_vocab.txt"

testing:
    beam_size: 5
    alpha: 1.0

training:
    random_seed: 42
    optimizer: "adam"
    adam_betas: [0.9, 0.999]
    scheduling: "plateau"
    loss: "crossentropy"
    learning_rate: 0.002
    learning_rate_min: 0.00000001
    label_smoothing: 0.1
    weight_decay: 0.0
    batch_size: 250
    batch_type: "token"
    epochs: 30
    validation_freq: 1000
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/transformer_reverse"
    overwrite: True
    shuffle: True
    use_cuda: False
    max_output_length: 30
    print_valid_sents: [0, 3, 6, 9]
    keep_last_ckpts: 2


model:
    initializer: "xavier"
    embed_initializer: "xavier"
    embed_init_gain: 1.0
    init_gain: 1.0
    bias_initializer: "zeros"
    tied_embeddings: True
    tied_softmax: False
    encoder:
        type: "transformer"
        num_layers: 2
        num_heads: 3
        embeddings:
            embedding_dim: 30
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 30
        ff_size: 120
        dropout: 0.3
    decoder:
        type: "transformer"
        num_layers: 2
        num_heads: 3
        embeddings:
            embedding_dim: 30
            scale: True
            dropout: 0.
        # typically ff_size = 4 x hidden_size
        hidden_size: 30
        ff_size: 120
        dropout: 0.3
